name: healthhub
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  cupertino_icons: ^1.0.6
  mongo_dart: ^0.10.3
  intl: ^0.17.0
  email_validator: ^2.0.1
  shelf: ^1.4.1
  http: ^0.13.5
  logging: ^1.0.2
  contacts_service: ^0.6.2
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/logo.png
    - assets/Doctor.png
    - assets/Pharmacy.png
    - assets/Hospital.png
    - assets/Ambulance.png
    - assets/home.png
    - assets/doctor1.png
    - assets/doctor2.png
    - assets/doctor3.png
    - assets/doctor4.png
    - assets/dashboardLady.png
